### ISSUE TITLE
Discussions MVP List

### ISSUE THREAD

**Issue by michaelmirandi** [ergo-pad/paideia-frontend#65]
## Discussions
- [x] Remove on delete, remove a user's profile image
- [x] Expand comments by default, click on the line to close 
- [x] Activities integration
- [ ] Notification integration
- [x] Search fix and filters
- [x] Comments ws fix
- [x] Profile page cleanup (wallet info, follow, tokens, proposal listing)
- [x] Likes / dislikes, favorites persist
- [x] Followers, created, and approve
- [x] Ergo mobile wallet display
- [x] Correct amount of token displayed (wallet & profile page)
- [x] Fix styling on large screens (gitbooks)
- [x] Click to close nav
- [x] Active proposals width fix
- [x] Notifications style fix
- [x] Error connecting to dao (no dao tokens)
- [x] Grey out proposals
- [x] Categories: New Feature, Finance, General, Governance, Development
- [x] On cancel, direct back to dashboard
- [x] Add collapse onto dao config switches
- [x] Token information grid item container
- [x] Verify TinyMCE domain
- [x] Drag & drop files

## Creation
- [ ] Side nav height
- [ ] Dao existing name check
- [ ] DAO url read only
- [ ] Warning Style fix
- [ ] Disable create a new token
- [ ] API Integrations
- [ ] Collapse animation with transition group on all switches
- [ ] Disabled delete when only 1 available
- [ ] Support needed (0-100), 51 less
- [ ] Remove token holder addresses & token amount for existing tokens
- [ ] Cancel -> Bring you back to landing (popup with warning)
- [ ] Saved drafts in the upper right corner with a dialog, similar to notifications

## Frontend
- [ ] add snackbar timeout to disappear
- [ ] DAO stats live data rather than dummy data
- [x] make proposal img area drag & drop
- [x] add link for mobile wallet login because you can't scan a QR code on your phone when you're browsing on your phone
- [ ] disable sliders in user notification settings as we don't support email and mobile notifications yet
- [ ] add ability for users to delete their comments
- [ ] in mobile, sidebar doesn't have a "close" or "retract" button
- [ ] Proposal filter is still placeholders

## Bugfix
- [x] Fix "Mine" tab under proposals to show only your proposals
- [x] "Mine" tab throws an error if no user is logged in. Hide tab if user not logged in. 
- [x] 404 under DAOs reverts to layout for the main website, not the dApp
- [x] "No proposals yet" defaults to website layout. 
- [x] when you navigate directly to dao/members or dao/proposals it defaults to website layout
- [x] Nautilus connected users can't change their profile pic or profile info. It doesn't save, just spins
- [ ] #80
- [ ] #81
- [x] #82

## Optimizations
- [ ] User profile images are not optimized on the backend. They load the full size image, even when displayed at 81x81 px. This should be done server side to the max image size expected, and can also be optimized further using next/image with the "size" prop

**Comment by michaelmirandi** [comment]
No dao can be named dashboard lol

**Comment by michaelmirandi** [comment]
Activities, create view to avoid joins using sqlalchemy (simpler and faster)

**Comment by michaelmirandi** [comment]
Add search fixes & sort by dropdown

**Comment by esot321c** [comment]
When you choose "Mine" under proposals, it doesn't just show yours

**Comment by esot321c** [comment]
Add ability for a user to delete their own comments

**Comment by michaelmirandi** [comment]
For 404, add a context and make a flag when throwing 404
