### ISSUE TITLE
Switch Discussions to Markdown

### ISSUE THREAD

**Issue by esot321c** [ergo-pad/paideia-frontend#75]
The TinyMCE platform gives users too many options and allows them to break dark/light mode. 

I propose we switch to Markdown since we have a built in markdown render already and it will be a lot easier to control what colors and layouts users can use. They don't need Geocities level control or we'll end up with a MySpace profile situation ;)

**Comment by michaelmirandi** [comment]
Fair enough! What have you guys used before in the past to render the markdown on the frontend?

**Comment by esot321c** [comment]
We've already got markdown rendering in place on Paideia. Just need to have
the text entry area setup for user's side

**Comment by esot321c** [comment]
https://github.com/ergo-pad/paideia-api/pull/44

**Comment by esot321c** [comment]
Final PR https://github.com/ergopad/paideia-app/pull/26
