### ISSUE TITLE
Dynamic Dao Integration (Banners, Photos, Proposals, Members)

### ISSUE THREAD

**Issue by michaelmirandi** [ergo-pad/paideia-frontend#80]

**Comment by michaelmirandi** [comment]
Need to alter /dao api endpoint to display token, ticker, logo img, and name. Will use this for dao listing page along with the dao picker.

**Comment by esot321c** [comment]
Trapper will create views in postgres for this

**Comment by michaelmirandi** [comment]
- [ ] Cleanup Dao Selector
- [ ]  Integrate dao membership check with API
- [ ] Connect wallet button in upper right if no membership

**Comment by michaelmirandi** [comment]
Think we should do a dao membership check on the backend as well when we call the 
/api/users/create_user_profile. This will ensure that only users with the token can create a profile in our db.

**Comment by esot321c** [comment]
Note that currently EGIO shows banner, description, etc, but on the proposals page it's still hardcoded to paideia proposals

**Comment by esot321c** [comment]
https://github.com/ergopad/paideia-app/pull/28

Going further is blocked by an endpoint that checks what tokens a user holds against what DAOs exist.
