### ISSUE TITLE
Switch from using consecutive ID numbers to UUIDs - URLs should use slugs not IDs

### ISSUE THREAD

**Issue by esot321c** [ergo-pad/paideia-frontend#83]
- For users especially, but DAOs as well and anything else requiring an ID, please use UUIDs. 
- URLs and routing should be built with slugs, not IDs

**Comment by esot321c** [comment]
This was recommended to ensure user data can't be skimmed as easily

**Comment by michaelmirandi** [comment]
Not sure I agree with swapping IDs for slugs. Why would we do this?

**Comment by esot321c** [comment]
IDs switched to UUID so people can't just scan the website by putting in number order

Slugs because it makes for much better URLs when you share them

Paideia.im/Dao/Paideia/proposal/save-the-dao

Vs

Paideia.im/Dao/1/proposal/13

**Comment by esot321c** [comment]
I think using slugs means you can leave ID consecutive and not have any concerns. I would just maybe not share the ID since that's more for an internal database than user-facing.

**Comment by esot321c** [comment]
I'm going to create a new issue that doesn't include UUIDs since that will make the database inefficient. We can just obfuscate the IDs from users and keep those as an internal database mechanism. 

Switching to URL slugs will enable that
