### ISSUE TITLE
Refactor routing

### ISSUE THREAD

**Issue by esot321c** [ergo-pad/paideia-frontend#87]
next routes should be like this: 

/dao/[id].tsx
/dao/index.tsx

currently paideia is like this: 

/dao.tsx
/dao/[id].tsx

There are several routes that are blank pages that load another route. This seems to be because Paideia is hardcoded at /dao

Lets eliminate having paideia hardcoded at /dao and clean up the routes so they're less confusing and easier to maintain.

**Comment by michaelmirandi** [comment]
Think this will cause conflicts, can show you on a call

**Comment by esot321c** [comment]
Created a new repo https://github.com/ergopad/paideia-app

The regular website will be at paideia.im and will remain the paideia-frontend repo, and the app will be at app.paideia.im. This resolves some layout issues, 404 issues, and a lot of manual filtering that was happening.

**Comment by esot321c** [comment]
one left: 
/distribution/
/distributions/

**Comment by esot321c** [comment]
Update addendums

**Comment by esot321c** [comment]
https://github.com/ergopad/paideia-app/pull/8

Cleaned up the routing and updated the navbar. Cleaned up the navbar functionality a bit while I was there. It now navigates to the main sub-selection when clicking to open the accordion. 

This PR also locks in next 12.2.6 to prevent update to 13, which requires react 18, which breaks our charts.
