### ISSUE TITLE
Use URL slugs instead of IDs

### ISSUE THREAD

**Issue by esot321c** [ergo-pad/paideia-frontend#91]
I believe URL slugs are cleaner, better for sharing, improve SEO, and prevent malicious actors from skimming user data by running through consecutively numbered URLs. 

Let's switch from using IDs in urls like `paideia.im/dao/12/proposal/11` to slugs like `paideia.im/dao/egio/proposal/change-dao-name`

**Comment by michaelmirandi** [comment]
I agree with the dao slug, and this is how it currently is, not the proposal id though. Think this makes it extremely difficult to query

**Comment by esot321c** [comment]
Hey @michaelmirandi I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/ergopad-61d81ca6dcb164001f328891/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [Zenhub](https://www.zenhub.com)_
